//user related
export const FETCH_USER = 'FETCH_USER';

//fetch form related
export const FETCH_FORM_ADMIN = 'FETCH_FORM_ADMIN';
export const FETCH_FORM_ADMIN_START = 'FETCH_FETCH_FORM_ADMIN_STARTFORM_START';
export const FETCH_FORM_ADMIN_SUCCESS = 'FETCH_FORM_ADMIN_SUCCESS';
export const FETCH_FORM_ADMIN_FAILED = 'FETCH_FORM_ADMIN_FAILED';

//dash related
export const FETCH_FORMS_START = 'FETCH_FORMS_START';
export const FETCH_FORMS_SUCCESS = 'FETCH_FORMS_SUCCESS';
export const FETCH_FORMS_FAILED = 'FETCH_FORMS_FAILED';
export const DELETE_FORM_START = 'DELETE_FORM_START';
export const DELETE_FORM_SUCCESS = 'DELETE_FORM_SUCCESS';
export const DELETE_FORM_FAILED = 'DELETE_FORM_FAILED';
export const RENAME_FORM_START = 'RENAME_FORM_START';
export const RENAME_FORM_SUCCESS = 'RENAME_FORM_SUCCESS';
export const RENAME_FORM_FAILED = 'RENAME_FORM_FAILED';

//form questions related
export const INIT_FORM = 'INIT_FORM';
export const ADD_QUESTION = 'ADD_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const MODIFY_FORM_PROPERTIES = 'MODIFY_FORM_PROPERTIES';
export const UPDATE_SEQUENCE = 'UPDATE_SEQUENCE';
export const UPDATE_LOGIC = 'UPDATE_LOGIC';
export const DELETE_SEQUENCE = 'DELETE_SEQUENCE';

//public operation related
export const FETCH_FORM_START = 'FETCH_FORM_START';
export const FETCH_FORM_SUCCESS = 'FETCH_FORM_SUCCESS';
export const FETCH_FORM_FAILED = 'FETCH_FORM_FAILED';
export const SYNC_STATE = 'SYNC_STATE';
export const LOAD_STATE = 'LOAD_STATE';
export const RESUME_STATE = 'RESUME_STATE';

//context related
export const UPDATE_CONTEXT = 'UPDATE_CONTEXT';

//feedback related
export const FETCH_ALL_FEEDBACKS = 'FETCH_ALL_FEEDBACKS';
export const FETCH_ALL_FEEDBACKS_SUCCESS = 'FETCH_ALL_FEEDBACKS_SUCCESS';
export const FETCH_ALL_FEEDBACKS_FAILED = 'FETCH_ALL_FEEDBACKS_FAILED';
export const ADD_POST = 'ADD_POST';
