const { ObjectID } = require('mongodb');

const populateQuestions = () => {
    const dummy1 = {
        _id: new ObjectID(),
        title: 'Nan Zhu Jiao',
        description: 'Generated by Test API',
        validation: '{"isRequired":false,"minCharCount":"","maxCharCount":""}',
        sequence: 1,
        type: 'LONG_TEXT'
    };

    const dummy2 = {
        _id: new ObjectID(),
        title: 'Nv Zhu Jiao',
        description: 'Generated by Test API',
        validation: '{"isRequired":false,"minCharCount":"","maxCharCount":""}',
        sequence: 2,
        type: 'EMAIL'
    };

    const dummy4ID = new ObjectID();
    const dummy5ID = new ObjectID();

    const dummy3Connect = [
        { key: 0, qid: dummy4ID.toString() },
        { key: 1, qid: dummy5ID.toString() }
    ];

    const dummy3 = {
        _id: new ObjectID(),
        options: [
            'Bei Tai Yi Hao',
            'Bei Tai Er Hao',
            'Bei Tai San Hao',
            'Zai Jian Qian Ren'
        ],
        title: 'Bei Tai Nan',
        description: 'Generated by Test API (4 Options)',
        validation: '{"isRequired":false,"minCharCount":"","maxCharCount":""}',
        sequence: 3,
        connect: JSON.stringify(dummy3Connect),
        type: 'SINGLE_CHOICE'
    };

    const dummy4 = {
        _id: dummy4ID,
        title: 'Tuo Xi Nv',
        description: 'Generated by Test API',
        validation: '{"isRequired":false,"minCharCount":"","maxCharCount":""}',
        sequence: 4,
        type: 'NUMBER'
    };

    const dummy5 = {
        _id: dummy5ID,
        title: 'Yao Yan Jian Huo',
        description: 'Generated by Test API',
        validation: '{"isRequired":false,"minCharCount":"","maxCharCount":""}',
        sequence: 5,
        type: 'LINK'
    };

    const dummy6 = {
        _id: new ObjectID(),
        title: 'Da Mo Wang',
        description: 'Generated by Test API',
        validation: '{"isRequired":false,"minCharCount":"","maxCharCount":""}',
        sequence: 6,
        type: 'YES_NO',
        options: ['Wo Shi', 'Wo Bu Shi']
    };

    return [dummy1, dummy2, dummy3, dummy4, dummy5, dummy6];
};

module.exports = { populateQuestions };
